### ISSUE TITLE
Article setting may not be evaluated correctly

### ISSUE THREAD

**Issue by jbaughman** [idsproject/ILLiad_Addons#1]
https://github.com/idsproject/ILLiad_Addons/blob/ca8d3c48e6789dd8192af19cfb32efdcabc01edb/GoogleCombined/GoogleCombined.lua#L58

While reviewing this addon for the ILLiad Addons directory, I noticed an issue with this line. The 'Article' setting is a string and is intended to be either true or false, but I believe this comparison of the setting's string to a literal false will return will always evaluate to false if the string isn't empty or null. I think the setting should either be a boolean or the comparison here should compare against a string value, e.g. 'false'. Considering that you'd have to worry about case sensitivity for the string comparisons, I'd imagine changing the setting type is going to be easier.

**Comment by Kerwick** [comment]
Boolean error fixed
